name: .NET 真正的安检站

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # 取下书架上的代码

    - name: 安装 .NET 8 大脑
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0

    - name: 真正的编译检查
      run: dotnet build
